# Generated by Django 5.2.12 on 2026-04-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0005_newsarticle_newsarticleresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantsession',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='demographics_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='education_level',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='gender',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='movies_per_week',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='picture_statement_agreement',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='profession',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='reading_habits_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='reads_news_daily',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='reads_words_daily',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
