# Generated by Django 5.2.12 on 2026-04-01 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0006_participantsession_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('context', models.TextField()),
                ('nodes', models.JSONField(default=list)),
                ('edges', models.JSONField(default=list)),
                ('question_one', models.CharField(max_length=255)),
                ('question_one_options', models.JSONField(default=list)),
                ('question_two', models.CharField(max_length=255)),
                ('question_two_options', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='NetworkDiagramResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_one', models.CharField(max_length=255)),
                ('answer_two', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey_app.networkdiagram')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_diagram_responses', to='survey_app.participantsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'diagram'), name='unique_network_response_per_participant')],
            },
        ),
    ]
